### ISSUE TITLE
coding restore tidak berfungsi

### ISSUE THREAD

**Issue by belcod** [GaroPpo/Backup-Restore-MySQL-Using-VB.Net#1]
untuk coding backup sangat simpel dan bekerja dengan bagus, tapi untuk coding restore belum berfungsi, ketika di restore belum terjadi perubahan apa2 pada database

**Comment by GaroPpo** [comment]
Terima Kasih atas koreksinya Sdr. @belcod. Sebelumnya untuk proses restore Sdr. Belcod menggunakan platform XAMPP atau WAMP Server? Akan saya coba perbaharui sembari menunggu balasan dari Sdr. Belcod.

**Comment by GaroPpo** [comment]
untuk restore ada masalah jika menggunakan versi MySQL 8.0 ke atas. Script backup tetap berfungsi dengan normal, namun jika menggunakan MySQL 8.0 ke atas, backup database hanya membackup tanpa database sama sekali (File Kosong). Jadi ketika proses restore dilakukan, maka tidak terjadi apa-apa pada database. Sementara masih proses perbaikan. Sesegera mungkin saya update untuk MySQL 8.0. Terima kasih atas issue nya.
